xarm7_urdf: &arm_config
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005

xarm7_urdf_manipulator: *arm_config